runtime: nodejs12 
handlers:
- url: /
  static_files: ../angular-app/dist/angular-app/index.html
  upload: ../angular-app/dist/angular-app/index.html
- url: /
  static_dir: ../angular-app/dist/angular-app